### **NUMPY & PANDAS**

In [ ]:
#tao array 1 chieu
!pip install numpy
import numpy as np

list = [1,2,3,4,5,6,7,8,12,3]

print("list: ", list)

number_array = np.array(list)

print("number array", number_array)

list:  [1, 2, 3, 4, 5, 6, 7, 8, 12, 3]
number array [ 1  2  3  4  5  6  7  8 12  3]


In [ ]:
c = np.array([(3,6,7),
              (2,4,9)])
print(c)
print(c.shape)#so hang so cot
print(c.dtype)#kieu du lieu

[[3 6 7]
 [2 4 9]]
(2, 3)
int64


In [ ]:
d = np.array([(2,3,5),
              (3,6,7),
              (3,6,9),
              (5,6,7)])
print(d)
print(d.shape)
print(d.dtype)

[[2 3 5]
 [3 6 7]
 [3 6 9]
 [5 6 7]]
(4, 3)
int64


In [ ]:
e = np.zeros((2,3))
f = np.ones((3,3))

print(e)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
j = np.array([(2,3,5), (3,6,9)])
print(j)
k = np.reshape(j, (3,2))#thay doi kich thuoc ma tran
print(k)

[[2 3 5]
 [3 6 9]]
[[2 3]
 [5 3]
 [6 9]]


In [ ]:
l = np.array([("con","me","may"),("me", "may", "beo")])
p = l.flatten()
print(p)

['con' 'me' 'may' 'me' 'may' 'beo']


In [ ]:
h = np.array([(2,3,5), (3,6,9)])
q = np.array([(2,3,5), (3,6,9)])
h_stack = np.hstack((h,q))
v_stack = np.vstack((h,q))
print(h_stack)
print(v_stack)

[[2 3 5 2 3 5]
 [3 6 9 3 6 9]]
[[2 3 5]
 [3 6 9]
 [2 3 5]
 [3 6 9]]


In [ ]:
w = np.random.randint(100, size = (5,))
print(w)
w = np.random.randint(100, size = (5,2))
print(w)
w = np.random.randint(100, size = (5,2,3))
print(w)

[34 65 80 44 69]
[[61 97]
 [ 9 20]
 [77 82]
 [86 95]
 [31 20]]
[[[23  6 54]
  [29 11 60]]

 [[59 12 73]
  [23 77 20]]

 [[29 51 94]
  [41 56  2]]

 [[34 71 68]
  [99 22 78]]

 [[46  5 77]
  [60 72 25]]]


In [2]:
#bai 1&2
# Tạo mảng 3x3 ngẫu nhiên từ 0 đến 20
arr = np.random.randint(0, 21, (3, 3))
print("Mảng khởi tạo:\n", arr)

# 1. Kiểm tra tất cả phần tử khác 0
check_all = np.all(arr != 0)
print("Tất cả phần tử khác 0:", check_all)

# 2. Kiểm tra tồn tại ít nhất một phần tử khác 0
check_any = np.any(arr != 0)
print("Có ít nhất một phần tử khác 0:", check_any)

Mảng khởi tạo:
 [[ 7 18 13]
 [ 8  4 16]
 [15 15 10]]
Tất cả phần tử khác 0: True
Có ít nhất một phần tử khác 0: True


In [3]:
#3
a = np.array([1, 5, 10])
b = np.array([1, 3, 12])

print("So sánh 1 chiều:")
print("Greater (a > b):", np.greater(a, b))
print("Less Equal (a <= b):", np.less_equal(a, b))

# 2 chiều
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[0, 2], [5, 1]])
print("\nSo sánh 2 chiều (Greater Equal): \n", np.greater_equal(matrix_a, matrix_b))

So sánh 1 chiều:
Greater (a > b): [False  True False]
Less Equal (a <= b): [ True False  True]

So sánh 2 chiều (Greater Equal): 
 [[ True  True]
 [False  True]]


In [4]:
#4
ones = np.ones(10)
zeros = np.zeros(10)
fives = np.ones(10) * 5 # Hoặc np.full(10, 5)

res = np.concatenate([ones, zeros, fives])
print("Mảng kết hợp:", res)

Mảng kết hợp: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [5]:
#5
even_arr = np.arange(30, 71, 2)
print("Mảng số chẵn:", even_arr)

Mảng số chẵn: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [6]:
#6
identity_matrix = np.identity(3)
print("Ma trận đơn vị:\n", identity_matrix)

Ma trận đơn vị:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#7
arr_7 = np.arange(15, 56) # Giả sử lấy số nguyên
print("Mảng từ phần tử thứ 2 đến kế cuối:", arr_7[1:-1])

Mảng từ phần tử thứ 2 đến kế cuối: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [8]:
#8
arr_8 = np.random.randint(0, 21, 20)
print("Mảng gốc:", arr_8)

# Đổi dấu những số từ 9 đến 15
arr_8[(arr_8 >= 9) & (arr_8 <= 15)] *= -1
print("Mảng sau khi đổi dấu:", arr_8)

Mảng gốc: [10 16 16  3  9 20  9 14 13 16 14  6  0 19 12  3  9  9  3 10]
Mảng sau khi đổi dấu: [-10  16  16   3  -9  20  -9 -14 -13  16 -14   6   0  19 -12   3  -9  -9
   3 -10]


In [9]:
#9
matrix_9 = np.random.randint(10, 22, (3, 4))
print("Ma trận 3x4:\n", matrix_9)

Ma trận 3x4:
 [[11 15 11 19]
 [15 12 20 15]
 [17 18 15 21]]


In [10]:
#10
matrix_10 = np.ones((10, 10))
matrix_10[1:-1, 1:-1] = 0
print("Ma trận biên 1:\n", matrix_10)

Ma trận biên 1:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [11]:
#11
diag_values = [1, 2, 3, 4, 5]
matrix_11 = np.diag(diag_values)
print("Ma trận đường chéo:\n", matrix_11)

Ma trận đường chéo:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [12]:
#12
arr_3d = np.random.randint(1, 10, (3, 3, 3))
print("Tổng theo mỗi dòng (axis 1):\n", np.sum(arr_3d, axis=1))
print("Tổng theo mỗi cột (axis 2):\n", np.sum(arr_3d, axis=2))

Tổng theo mỗi dòng (axis 1):
 [[26 17  9]
 [19 23 13]
 [18 17 19]]
Tổng theo mỗi cột (axis 2):
 [[15 16 21]
 [18 18 19]
 [18 20 16]]


In [13]:
#13
v1 = np.random.rand(10)
v2 = np.random.rand(10)
dot_product = np.dot(v1, v2)
print("Inner Product:", dot_product)

Inner Product: 1.5639182020554148


In [14]:
#14
A = np.random.randint(1, 10, (4, 3))
y = np.random.randint(1, 10, 3)

print("Ma trận A:\n", A)
print("Vector y:", y)

# Thực hiện cộng (Broadcasting)
result = A + y
print("Kết quả A + y:\n", result)

Ma trận A:
 [[9 1 6]
 [5 8 9]
 [1 4 1]
 [7 1 1]]
Vector y: [6 4 8]
Kết quả A + y:
 [[15  5 14]
 [11 12 17]
 [ 7  8  9]
 [13  5  9]]


In [16]:
#15
import pandas as pd
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


In [17]:
#16
# Tạo DataFrame mẫu từ ảnh
df_16 = pd.DataFrame({
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
})

# Sử dụng iloc thay cho ix (ix đã bị khai tử)
s_col1 = df_16.iloc[:, 0]
print("Cột đầu tiên dưới dạng Series:\n", s_col1)

Cột đầu tiên dưới dạng Series:
 0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


In [18]:
#17
df_17 = pd.DataFrame(np.random.randint(1, 10, (4, 3)), columns=['A', 'B', 'C'])
print("Mảng gốc:\n", df_17)

# Sắp xếp theo cột 'A'
df_sorted = df_17.sort_values(by='A')
print("Sắp xếp theo cột A:\n", df_sorted)

Mảng gốc:
    A  B  C
0  2  7  9
1  5  2  6
2  3  6  4
3  5  2  8
Sắp xếp theo cột A:
    A  B  C
0  2  7  9
2  3  6  4
1  5  2  6
3  5  2  8


In [19]:
#18
s_18 = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print("Gốc:\n", s_18)

# Thay đổi thứ tự index bằng reindex
s_new = s_18.reindex(index=['B', 'A', 'C', 'D', 'E'])
print("Sau khi reindex:\n", s_new)

Gốc:
 A    1
B    2
C    3
D    4
E    5
dtype: int64
Sau khi reindex:
 B    2
A    1
C    3
D    4
E    5
dtype: int64


In [20]:
#19
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

# Lọc các phần tử của sr1 không nằm trong sr2
result_19 = sr1[~sr1.isin(sr2)]
print("Items of sr1 not present in sr2:\n", result_19)

Items of sr1 not present in sr2:
 0    1
2    3
4    5
dtype: int64


In [21]:
#20
x = pd.Series(np.random.randint(1, 20, 20))
y = pd.Series(np.random.randint(1, 20, 20))

print("Hội (Union):", np.union1d(x, y))
print("Giao (Intersection):", np.intersect1d(x, y))

Hội (Union): [ 2  4  5  7  8  9 10 11 12 13 14 15 16 17 18 19]
Giao (Intersection): [ 2  4  5  7  8  9 10 11 12 13 14 15 16 18]


In [22]:
#21
x_21 = pd.Series([0, 1, 2, 7, 8, 9])
y_21 = pd.Series(['p', 'q', 'r', 'w', 'x', 'y'])

# Chiều dọc (Vertical)
ver = pd.concat([x_21, y_21], axis=0)
# Chiều ngang (Horizontal)
hor = pd.concat([x_21, y_21], axis=1)

print("Kết quả nối dọc:\n", ver)
print("Kết quả nối ngang:\n", hor)

Kết quả nối dọc:
 0    0
1    1
2    2
3    7
4    8
5    9
0    p
1    q
2    r
3    w
4    x
5    y
dtype: object
Kết quả nối ngang:
    0  1
0  0  p
1  1  q
2  2  r
3  7  w
4  8  x
5  9  y


In [23]:
#22
# Khởi tạo DataFrame chung cho các bài tiếp theo
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
print("#22 Hiển thị DataFrame:\n", df)

#23
print("\n#23 Ba dòng đầu tiên:\n", df.head(3))

#24
print("\n#24 Cột name và score:\n", df[['name', 'score']])

#25
print("\n#25 Những dòng có attempts > 2:\n", df[df['attempts'] > 2])

#26
print(f"\n#26 Số dòng: {df.shape[0]}, Số cột: {df.shape[1]}")

#27
print("\n#27 Các dòng có score là NaN:\n", df[df['score'].isnull()])

#28
print("\n#28 Các dòng có score trong khoảng [15, 20]:\n", df[df['score'].between(15, 20)])

#29
cond = (df['attempts'] > 2) & (df['score'].between(15, 20))
print("\n#29 Attempts > 2 và Score [15, 20]:\n", df[cond])

#30
df.loc['d', 'score'] = 19
print("\n#30 Thay đổi score dòng 'd' thành 19:\n", df.loc[['d']])

#22 Hiển thị DataFrame:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

#23 Ba dòng đầu tiên:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

#24 Cột name và score:
         name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

#25 Những dòng có attempts > 2:
       name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3   

###**TENSORFLOW**

In [24]:
import tensorflow as tf
import numpy as np

In [25]:
#1
t1 = tf.zeros([2, 3])
print("#1 Tensor zeros:\n", t1)

#1 Tensor zeros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [27]:
#2
X = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
t2 = tf.zeros_like(X)
print("#2 Tensor zeros_like X:\n", t2)


#2 Tensor zeros_like X:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [28]:
#3
t3 = tf.fill([3, 2], 5)
print("#3 Tensor filled with 5:\n", t3)

#3 Tensor filled with 5:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [29]:
#4 (Minh họa tạo 50 số chẵn bắt đầu từ 0)
t4 = tf.range(0, 100, 2) # Tạo 50 số chẵn đầu tiên
print("#4 50 số chẵn:\n", t4)

#5 Dãy số [10, 12, ..., 100]
t5 = tf.range(10, 101, 2)
print("#5 Dãy số từ 10 đến 100:\n", t5)

#4 50 số chẵn:
 tf.Tensor(
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98], shape=(50,), dtype=int32)
#5 Dãy số từ 10 đến 100:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [30]:
#6
t6 = tf.random.normal(shape=[3, 2], mean=0, stddev=2)
print("#6 Random Normal:\n", t6)

#6 Random Normal:
 tf.Tensor(
[[ 1.6027522   0.617661  ]
 [-0.02915484  1.136631  ]
 [-1.862092    1.0305709 ]], shape=(3, 2), dtype=float32)


In [31]:
#7
t7 = tf.random.uniform(shape=[3, 2], minval=0, maxval=2)
print("#7 Random Uniform:\n", t7)

#7 Random Uniform:
 tf.Tensor(
[[1.7034492  1.4537332 ]
 [0.0826292  0.68024325]
 [1.4810414  1.3676105 ]], shape=(3, 2), dtype=float32)


In [32]:
#8
X_8 = tf.constant([[1, 2], [3, 4], [5, 6]])
t8 = tf.random.shuffle(X_8)
print("#8 Shuffled X:\n", t8)

#8 Shuffled X:
 tf.Tensor(
[[3 4]
 [5 6]
 [1 2]], shape=(3, 2), dtype=int32)


In [33]:
#9
t9_large = tf.random.uniform((10, 10, 3))
t9_crop = tf.image.random_crop(t9_large, size=(5, 5, 3))
print("#9 Size sau khi crop:", t9_crop.shape)

#9 Size sau khi crop: (5, 5, 3)


In [34]:
#10
x = tf.random.uniform([5], 1, 10)
y = tf.random.uniform([5], 1, 10)
result_10 = tf.where(x < y, x + y, x - y)
print("#10 Kết quả điều kiện:\n", result_10)

#10 Kết quả điều kiện:
 tf.Tensor([ 4.0139503  12.200576    2.7365313   0.05452728  1.3780322 ], shape=(5,), dtype=float32)


In [35]:
#11
# Tạo tensor x kích thước (3, 2) với giá trị nguyên trong khoảng [5, 10]
x = tf.random.uniform(shape=(3, 2), minval=5, maxval=11, dtype=tf.int32)

# Tạo tensor y kích thước (2, 3) với giá trị nguyên trong khoảng [15, 20]
y = tf.random.uniform(shape=(2, 3), minval=15, maxval=21, dtype=tf.int32)

print("Tensor x (3x2):\n", x.numpy())
print("Tensor y (2x3):\n", y.numpy())

# Lấy các giá trị trên đường chéo của x
diag_x = tf.linalg.diag_part(x)
print("\nGiá trị đường chéo của x:", diag_x.numpy())

# Thực hiện x + y
y_transposed = tf.transpose(y)
result_11 = x + y_transposed

print("\nKết quả x + transpose(y) (kích thước 3x2):\n", result_11.numpy())

Tensor x (3x2):
 [[ 5  7]
 [10 10]
 [ 7  5]]
Tensor y (2x3):
 [[15 20 15]
 [16 17 15]]

Giá trị đường chéo của x: [ 5 10]

Kết quả x + transpose(y) (kích thước 3x2):
 [[20 23]
 [30 27]
 [22 20]]


In [37]:
#12: Các hàm cơ bản trong Graph
@tf.function
def basic_ops(a, b):
    return a + b, a - b, a * b, a / b

#13, #14, #15, #16: Xây dựng Model tính toán
class GeometryModel(tf.Module):
    @tf.function
    def tinh_tong(self, x, y): #13
        return x + y

    @tf.function
    def tinh_hieu_tich(self, x, y): #14
        return x - y, x * y

    @tf.function
    def chu_vi_hcn(self, a, b): #15
        return (a + b) * 2

    @tf.function
    def dien_tich_hinh_hop(self, a, b, c): #16
        s_xung_quanh = (a + b) * c * 2
        s_toan_phan = (a * b) * 2 + s_xung_quanh
        return s_toan_phan

model = GeometryModel()
print("#15 Chu vi HCN (a=5, b=3):", model.chu_vi_hcn(tf.constant(5.0), tf.constant(3.0)).numpy())

#15 Chu vi HCN (a=5, b=3): 16.0


In [38]:
#19: Ví dụ mô hình Đường trung bình tam giác
@tf.function
def check_duong_trung_binh(MN, BC, AM, MB):
    # Điều kiện 1: M là trung điểm AB (AM = MB)
    is_midpoint = tf.equal(AM, MB)
    # Điều kiện 2: MN song song BC và MN = BC/2
    is_parallel_and_half = tf.logical_and(tf.equal(MN, BC/2), True) # Giả định song song là True

    # Kết luận NA = NC
    return tf.logical_and(is_midpoint, is_parallel_and_half)

# Chạy thử
conclusion = check_duong_trung_binh(tf.constant(5.0), tf.constant(10.0), tf.constant(4.0), tf.constant(4.0))
print("#19 Kết luận NA=NC là:", conclusion.numpy())

#19 Kết luận NA=NC là: True
